name: todo_mobx
version: 1.0.0+1
description: A new Flutter project.
environment: 
  sdk: '>=2.1.0 <3.0.0'
dependencies: 
  path_provider: ^1.4.0
  hive: ">=1.1.1 <3.0.0"
  flutter_mobx: ">=0.3.3+1 <3.0.0"
  mobx: ">=0.3.9+1 <3.0.0"
  dio: ">=3.0.4 <6.0.0"
  rxdart: ^0.22.6
  bloc_pattern: ^2.5.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  mobx_codegen: ">=0.3.10 <3.0.0"
  build_runner: ^1.7.2
  mockito: ">=4.1.1 <6.0.0"
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true

scripts:
  build: flutter pub run build_runner build
  clean: flutter pub run build_runner clean